#include<iostream>
#include<string>
#include<sstream>
#include<map>
#include<vector>

using namespace std;

int main(){
	string str="Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for Geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for Geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks"
	"Geeks for geeks is one of the the geeks for geeks in the world of Geeks";

	stringstream my_str(str);
	map<string,int> m;
	string kk;
	while(my_str>>kk){
		m[kk]++;
	}

	map<string,int>::iterator it=m.begin();
	for( ;it!=m.end();it++){
		cout<<it->first<<"->"
			<<it->second<<endl;
	}
	return 0;
}